apiVersion: v1
kind: Service
metadata:
  name: mivaa-pdf-extractor
  namespace: default
  labels:
    app: mivaa-pdf-extractor
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "mivaa-lb"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-interval-seconds: "10"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "2"
spec:
  type: LoadBalancer
  selector:
    app: mivaa-pdf-extractor
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  sessionAffinity: None  # No sticky sessions needed (stateless)

